name: Rhino Code Coverage

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Some tests require more CPU, and all can use multiple CPUs
      max-parallel: 1
    name: Rhino Tests
    steps:

    - name: Check out Rhino
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Check out test262
      # We don't actually want all the history for this part
      run: git submodule update --init --single-branch

    - name: Set up Java
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        java-version: 21
        distribution: 'adopt'

    - name: Build and test
      run: >-
        ./gradlew test testCodeCoverageReport

    - name: Upload results
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      if: ${{ always() }}
      with:
        name: reports-java-21
        path: '*/build/reports/jacoco'